// <auto-generated />
using System;
using LawPavillion.LibraryManagement.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawPavillion.LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120112219_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LawPavillion.LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Wield C. Thompson",
                            ISBN = "9780132350884",
                            PublishedDate = new DateTime(2007, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Object Oriented Programming"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Eric Evans",
                            ISBN = "9780321125217",
                            PublishedDate = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Andrew Hunt & David Thomas",
                            ISBN = "9780201616224",
                            PublishedDate = new DateTime(1999, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Kleppmann",
                            ISBN = "9781449373320",
                            PublishedDate = new DateTime(2017, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Designing Data-Intensive Applications"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert T. Kiyosaki",
                            ISBN = "9781612680194",
                            PublishedDate = new DateTime(1997, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Benjamin Graham",
                            ISBN = "9780060555665",
                            PublishedDate = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Intelligent Investor"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Morgan Housel",
                            ISBN = "9780857197689",
                            PublishedDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Psychology of Money"
                        },
                        new
                        {
                            Id = 8,
                            Author = "C.S. Lewis",
                            ISBN = "9780060652920",
                            PublishedDate = new DateTime(1952, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mere Christianity"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Rick Warren",
                            ISBN = "9780310337508",
                            PublishedDate = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Purpose Driven Life"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.I. Packer",
                            ISBN = "9780830816507",
                            PublishedDate = new DateTime(1973, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knowing God"
                        });
                });

            modelBuilder.Entity("LawPavillion.LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
